language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: g4AOB1Wqp8WSxQ5M8quAzaPoKA4/O6kecFm2e7l7qOPgwGjvFCU5L2AIrKGOv6mSapWgmKQ8gXy2jJx0+lrgxCbgM3v/QCZEPCAm43P1AUoyi+VqR8tssc23UVOIHsuJcqmjJMZswWyQ94efYMQyOQDQQ6sROxKDGcdXaEBkZtSnFSKV2ybnM7WadE55orsFTuJ4TFUaf4/HR8iTtVjnhDe/U5jOfKIWiSd6w45u7sq+X/WplX1sJXPyf4AGdLa9ZnyClEE5L8ZI549IwrIvMV+sRzlJxdTsE95nk9mwLfHmh9BpaQMyIARPevv8S1DWFff1H7A/1bHCA1ETfCEYTlnMoCHYox8+4sqbhK4DDFuK5vRmSPtZUNgxYp522A7spMr9lf9KpxSTpiDhiAafUO2NCDtoH9svc0SaIiH9lGLZnSFoI3OM4xDfkFNXnIBmn2lpyr2AJiVgRYXALUrv9KnHoqudiYKMJK9Xnvbz1Ay42gDxOiKKA6RdPk/sNdz+uyVV68mZ2eRmPGYvoNPDSYpNHYSB74LjBuzZLtRjO55pZZZss4InmQSVOK0TalNhk5OaqyIfTYTHrnuYDCASTs3U+YUt04g4zh+GDYiYQgzrLn1Lg3TM1zxHECnSFJNBkpLt8/cvqsSYNzIPEh+u+TvPUZnA6MnB0YpnqkTZsj4=
  app: vmtips