language: java
jdk:
- oraclejdk8
deploy:
  api_key:
    secure: bWFK8W/GcrXIXPnPivG/uA9Dt0xj4lqFoJwvzZKF/Tomfb5ocr/hN8v4e5iGWoYkZMQR7iWHIIWn3wCtZnrKpVXDwSifhBdLVSEeYuJ9LxUhkxdCdh+NM2lYZZGhASteKhtstKDPEJnRn3+79LXZ6qdOuujv1mHE31yFBY1svma45t0IECVKgvNpanOZXStawRV++cZvfPp9xmIGiLcY0UfeesmnulW/AwWejK7oa3pXBcN1GWfzd7dam5AjAD/ExSd3OCbfsQTdn+s4cw+oJK1OvDhTpQlOfGtJALc5SWw0Q5EUlr93MELaBew3XWOi6YFszK3qdcSjHjxACLrto2wjGjyTJoVUy1kitXxOlKVf0uplCxdEKw51lZJuvVuPYJJo8+vll5idu5Na+9W2ipnZJcckeuJbkRI363dZn5t2ExCe02DNkK5cGCPOsNZhF3GQIWITiahk2qpoK5Gjkz8MdAtRDDdkw9zCru5LZfVNqnPKzEmj+rHSEZOmhNFEZaYeqqypjYq6UYp+pZ0ZQksCCH3XDYjN9N5G8f6d7rOhQzcbbvgj44xOw32kfy8oCZJAzuhbqZPbywQDo+EZc/irqa2189w4KEKLo3Zo4peopn0LFR4VNrdDZPUvOCPcqkdJ1AF5EQK4hBRW8RYsj+3V0C/8Bp+dqPE8FCJWo34=
    app: vmtips